### ISSUE TITLE
Magisk repo? 

### ISSUE THREAD

**Issue by pidus** [nongthaihoang/unicode_google_sans_font#1]
I just found that, submission of this module was rejected by Magisk bot, hence, it's not available in Magisk repo. Why is that? This is the most complete font module I have found. Unavailability in the repo seriously hinders the usage level of this module. :-(

**Comment by nongthaihoang** [comment]
Thanks for your kind words. 😁
I submitted my module on Magisk repo. It was rejected. There are three possible reasons:
- They stop accepting font modules anymore. 
- There's already a Google Sans font module on the repo. 
- They didn't actually know value of the module. 
It's a waste, isn't?

**Comment by linuxandria** [comment]
> Thanks for your kind words. 
> I submitted my module on Magisk repo once. And it was rejected. There are three possible reasons:
> 
> * They stop accepting font modules.
> * There's already a Google Sans font module.
> * They didn't actually know the value of the module.
>   It's a waste, isn't?

Worth noting now only Font changer is on the repo - and the maker of the module is a repo admin

**Comment by d-l-n** [comment]
topjohnwu (magisk creator) said that the only font module on magisk official repo will be font changer because it has "all" the fonts that have an individual module
Anyway, soon will be possible to add unofficial repos to magisk ;D

**Comment by nongthaihoang** [comment]
Thanks for the update. I knew about font changer. That's why I created the Android font patcher. But then the license issue came. 😅
The unofficial magisk repo seems promising.
