### ISSUE TITLE
Chữ e chưa giống lắm

### ISSUE THREAD

**Issue by Cutetlaem** [nongthaihoang/unicode_google_sans_font#2]
Chữ e trong Logo của Google nó hơi ngẩng lên bác ơi, chữ e hiện tại khá giống chữ e mặc định!

**Comment by nongthaihoang** [comment]
Tôi chưa hiểu bạn đang muốn nói gì? "chữ e chưa giống lắm" là giống cái gì? "Chữ e trong logo Google nó ngẩng lên" thì sao? Như thế nào là "chữ e hiện tại" và "chữ e mặc định"?
Bạn cần nói rõ điều bạn mong muốn là gì.

**Comment by Cutetlaem** [comment]
Ý mình là chữ "e" ở Logo của Google nó hơi nghiêng lên một tí, còn ở font vẫn là nằm ngang, bạn có thể chỉnh cho nó giống như trong logo của Google ở phiên bản tới không?

**Comment by nongthaihoang** [comment]
Cám ơn ý kiến của bạn. GS là một font đơn giản và lịch sự. Là kiểu chữ mà bạn có thể dùng hằng ngày. Đáng tiếc là mong muốn của bạn thiên về font trang trí hơn.

**Comment by Cutetlaem** [comment]
Bạn ơi, chữ "Đ" nó hơi "thon" làm nó mờ đi, chỉ mờ khi là chữ hoa thôi, còn "đ" thì vẫn ok!

**Comment by nongthaihoang** [comment]
Tôi chỉ sửa lỗi thôi bạn. Còn kiểu chữ như thế nào là do font chữ được thiết kế như thế ấy.
