### ISSUE TITLE
Miui Bản Mới Lỗi Đậm Nhạt Trên Statusbar

### ISSUE THREAD

**Issue by phamthanhbaolong** [nongthaihoang/unicode_google_sans_font#3]
![Screenshot_2019-08-23-15-10-47-632_com android chrome](https://user-images.githubusercontent.com/48144697/63577274-409a0200-c5b8-11e9-8bd0-05522a3b9baf.jpg)
Mong Anh Fix Lỗi Này Ạ

**Comment by nongthaihoang** [comment]
Bạn có thể cho tôi xem tấm hình "bình thường - ko lỗi"?

**Comment by phamthanhbaolong** [comment]
> Bạn có thể cho tôi xem tấm hình "bình thường - ko lỗi"?

### **ĐÂY TẤM KHÔNG LỖI ĐÂY Ạ CHỮ NÓ ĐẬM HƠN ANH Ạ. EM DÙNG FONT SAN FRANSICO NÓ HIỂN THỊ BÌNH THƯỜNG Ạ**

> 

> https://drive.google.com/file/d/12MeY-1LJAEyNgm7YRfU1TBAOeBbmAsFL/view?usp=drivesdk

**Comment by nongthaihoang** [comment]
Đó ko phải là font mặc định. Bạn hãy đưa máy trở về font ban đầu để thấy điều cần thấy.
