### ISSUE TITLE
IPA phonetic symbols mismatch

### ISSUE THREAD

**Issue by moposx** [nongthaihoang/unicode_google_sans_font#4]
I am a fan of Google Sans and thank you for bringing it onto Android with FULL functionality. I just got a little trouble today. I'm on MIUI11 based on Android Pie, and while I was inputing the IPA phonetic symbols I noticed that there were two same characters on the GBoard. In fact they should be two different symbols: `x` and `χ`.

![Screenshot_2019-10-17-11-22-34-548_com miui home](https://user-images.githubusercontent.com/15135544/66985443-642c8500-f0ef-11e9-9a6f-f80e2b0fbd9f.jpg)

Then I rebooted the phone disabling the Unicode Google Sans module, restoring the default Roboto font:

![Screenshot_2019-10-17-11-20-17-746_com miui home](https://user-images.githubusercontent.com/15135544/66985715-f5036080-f0ef-11e9-885a-d3d2a80215a1.jpg)

As the screenshots suggest, the unicode google sans seemed to mistake that two symbols. 
Hoping them to be fixed soon!

**Comment by nongthaihoang** [comment]
I see. I'll check if Google fixed it or I'm gonna do it myself. 
Thank you.

**Comment by nongthaihoang** [comment]
Just let you know that i'm working on an update to fix the issue.
