### ISSUE TITLE
How do I get Pixel-like fonts? (A mix of Roboto and GSans)

### ISSUE THREAD

**Issue by bohrabhijeet** [nongthaihoang/unicode_google_sans_font#5]
Google Pixel's font isn't Google Sans systemwide. I'd like to set mine like Pixel's. Is there an option? Can you guide me, please? 
Thanks.

**Comment by nongthaihoang** [comment]
There is a option to install this font for headline.

**Comment by bohrabhijeet** [comment]
Alright, thanks for the answer.

**Comment by bohrabhijeet** [comment]
Hi again, I'm still not able to get Google Sans in the status bar. Can you please point out what I'm doing wrong? 

Device: OnePlus 7
OS: Oxygen OS Open Beta 8
Android version: 10
Module version: 6.4.1-eol

**Comment by nongthaihoang** [comment]
Oxygen OS uses Regular style on its status bar while most Android device include Pixel use Medium one. You can't get separate GS for status bar from install this font.
