### ISSUE TITLE
Request for Bold and Italic support!!

### ISSUE THREAD

**Issue by Mikesew1320** [nongthaihoang/unicode_google_sans_font#7]
The fonts found in this module doesn't support Bold and Italic text styles. Can u add it please?

I mean if it's possible.

I checked this by extracting the ##Roboto_Regular.ttf file from the module and setting it as a custom font on my Telegram app BGram. Finally when I use bold and Italic styles. I can't see the styles but they are changed to those styles.

Also tried with other Telegram clients but it's the same.

What do you think on this?

**Comment by nongthaihoang** [comment]
I don't know what your talking about.

**Comment by nongthaihoang** [comment]
We had a conversation. It turned out he didn't know what he's doing. He used Roboto-Regular.ttf for his app. But he want it to be Bold and Italic too.
